Repository jenkinsci/support-core-plugin, pull requests merged in 2020-12, with the labels that each got.

#250 Remove the . for the all loggers entry
  src/main/java/com/cloudbees/jenkins/support/impl/LoggerManager.java
Labels: enhancement

#251 [FIXED JENKINS-64601] Improve write performance for big files under $JENKINS_HOME/logs/tasks/ by using BufferedOutputStream instead of OutputStream
  src/main/java/com/cloudbees/jenkins/support/util/IgnoreCloseOutputStream.java
Labels: bug

#253 Complete changelog and link to releases page
  CHANGELOG.md
Labels: chore
