Repository jenkinsci/support-core-plugin, pull requests merged in 2020-11, with the labels that each got.

#240 [JENKINS-35342] Allow to download a bundle
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/resources/com/cloudbees/jenkins/support/Messages.properties
  src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
  src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
Labels: feature

#228 [JENKINS-62746] Add remoting version details to about.md
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
  src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
Labels: enhancement

#233 [JENKINS-63722] Fix getId() of nested components
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
  src/main/java/com/cloudbees/jenkins/support/impl/JVMProcessSystemMetricsContents.java
  src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
  src/main/resources/com/cloudbees/jenkins/support/Messages.properties
  src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
  src/test/java/com/cloudbees/jenkins/support/SupportPluginTest.java
Labels: bug

#239 JENKINS-64172: Support Action names are made distinct
  src/main/java/com/cloudbees/jenkins/support/BundleFileName.java
  src/main/java/com/cloudbees/jenkins/support/BundleNameInstanceTypeProvider.java
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemAction.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportComputerAction.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportObjectAction.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportRunAction.java
  src/main/resources/com/cloudbees/jenkins/support/actions/Messages.properties
  src/test/java/com/cloudbees/jenkins/support/BundleFileNameTest.java
  src/test/java/com/cloudbees/jenkins/support/BundleNamePrefixTest.java
Labels: enhancement

#231 [JENKINS-63674] Capture full thread-dumps when there is a high CPU usage
  src/main/java/com/cloudbees/jenkins/support/threaddump/HighLoadComponent.java
  src/main/java/com/cloudbees/jenkins/support/threaddump/HighLoadCpuChecker.java
  src/main/java/com/cloudbees/jenkins/support/timer/FileListCap.java
  src/main/resources/com/cloudbees/jenkins/support/threaddump/Messages.properties
Labels: feature
