Repository jenkinsci/support-core-plugin, pull requests merged in 2021-08, with the labels that each got.

#299 [JENKINS-66003] Make Agent Launch Logs component available in Computer action
  src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
  src/test/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogsTest.java
Labels: enhancement

#304 Fix test which will fail when upgrading to remoting 4.8 (i.e core 2.294)
  pom.xml
Labels: chore

#303 [JENKINS-60010] OtherLogs should not include GC Logs if activated with the JVM
  src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/OtherLogs.java
  src/test/java/com/cloudbees/jenkins/support/impl/OtherLogsTest.java
Labels: bug

#298 [JENKINS-66023] Ability to provide additional Stop Words
  README.md
  src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
  src/test/java/com/cloudbees/jenkins/support/filter/ContentMappingsTest.java
  src/test/resources/com/cloudbees/jenkins/support/filter/ContentMappingsTest/additionalStopWordsIncludedAsStopWord/support/additional-stop-words.txt
Labels: feature
