Repository jenkinsci/support-core-plugin, pull requests merged in 2021-04, with the labels that each got.

#246 [JENKINS-42012] Wrapper to make Channel.callAsync really async
  src/main/java/com/cloudbees/jenkins/support/AsyncResultCache.java
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
  src/main/java/com/cloudbees/jenkins/support/util/CallAsyncWrapper.java
Labels: bug

#271 [JENKINS-65097] Add information about websocket in nodes.md
  pom.xml
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
  src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
Labels: feature

#277 Revert #275 and update async-http-client update to 1.7.24.3
  pom.xml
Labels: dependencies
