Repository jenkinsci/support-core-plugin, pull requests merged in 2022-07, with the labels that each got.

#380 Improve support bundle generation page
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/java/com/cloudbees/jenkins/support/api/Component.java
  src/main/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFile.java
  src/main/java/com/cloudbees/jenkins/support/configfiles/ConfigFileComponent.java
  src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
  src/main/java/com/cloudbees/jenkins/support/impl/AboutBrowser.java
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
  src/main/java/com/cloudbees/jenkins/support/impl/AboutUser.java
  src/main/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitors.java
  src/main/java/com/cloudbees/jenkins/support/impl/AdvancedProcFilesRetriever.java
  src/main/java/com/cloudbees/jenkins/support/impl/AgentProtocols.java
  src/main/java/com/cloudbees/jenkins/support/impl/BuildQueue.java
  src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/DumpExportTable.java
  src/main/java/com/cloudbees/jenkins/support/impl/EnvironmentVariables.java
  src/main/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimit.java
  src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/HeapUsageHistogram.java
  src/main/java/com/cloudbees/jenkins/support/impl/ItemsContent.java
  src/main/java/com/cloudbees/jenkins/support/impl/JVMProcessSystemMetricsContents.java
  src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/LoadStats.java
  src/main/java/com/cloudbees/jenkins/support/impl/LoggerManager.java
  src/main/java/com/cloudbees/jenkins/support/impl/Metrics.java
  src/main/java/com/cloudbees/jenkins/support/impl/NetworkInterfaces.java
  src/main/java/com/cloudbees/jenkins/support/impl/NodeMonitors.java
  src/main/java/com/cloudbees/jenkins/support/impl/NodeRemoteDirectoryComponent.java
  src/main/java/com/cloudbees/jenkins/support/impl/OtherLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/ProcFilesRetriever.java
  src/main/java/com/cloudbees/jenkins/support/impl/RemotingDiagnostics.java
  src/main/java/com/cloudbees/jenkins/support/impl/ReverseProxy.java
  src/main/java/com/cloudbees/jenkins/support/impl/RootCAs.java
  src/main/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponent.java
  src/main/java/com/cloudbees/jenkins/support/impl/RunningBuilds.java
  src/main/java/com/cloudbees/jenkins/support/impl/SlaveCommandStatistics.java
  src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/SlaveLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/SystemConfiguration.java
  src/main/java/com/cloudbees/jenkins/support/impl/SystemProperties.java
  src/main/java/com/cloudbees/jenkins/support/impl/TaskLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
  src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
  src/main/java/com/cloudbees/jenkins/support/impl/UserCount.java
  src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestComponent.java
  src/main/java/com/cloudbees/jenkins/support/threaddump/HighLoadComponent.java
  src/main/java/com/cloudbees/jenkins/support/timer/DeadlockRequestComponent.java
  src/main/java/com/cloudbees/jenkins/support/timer/FileListCapComponent.java
  src/main/java/com/cloudbees/jenkins/support/timer/UnfilteredFileListCapComponent.java
  src/main/resources/com/cloudbees/jenkins/support/Messages.properties
  src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
Labels: enhancement

#376 [JENKINS-68417] Revert `LogRecord` tricks
  src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
Labels: bug

#377 [JENKINS-68743] Report if a node is marked offline
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
  src/test/java/com/cloudbees/jenkins/support/impl/AboutJenkinsTest.java
Labels: enhancement

#389 bump jenkins version and bom
  pom.xml
Labels: developer
