Repository jenkinsci/support-core-plugin, pull requests merged in 2022-03, with the labels that each got.

#341 [JENKINS-67940] Fix retrieval of rotated JDK 9+ GC logs
  src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
  src/test/java/com/cloudbees/jenkins/support/impl/GCLogsTest.java
Labels: bug

#342 `InflightRequest` should only parse `userAgent` if and when `SlowRequestChecker` needs it
  src/main/java/com/cloudbees/jenkins/support/slowrequest/InflightRequest.java
Labels: bug

#345 Update Site Id is added to Update Center component
  src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
Labels: enhancement

#347 [chore] Remove unnecessary flaky test
  src/test/java/com/cloudbees/jenkins/support/impl/TaskLogsTest.java
Labels: chore

#346 EOL JSR 305
  src/main/java/com/cloudbees/jenkins/support/BundleFileName.java
  src/main/java/com/cloudbees/jenkins/support/BundleNameInstanceTypeProvider.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportAbstractItemAction.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportComputerAction.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportObjectAction.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportRunAction.java
  src/main/java/com/cloudbees/jenkins/support/api/Content.java
  src/main/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration.java
  src/main/java/com/cloudbees/jenkins/support/config/SupportPluginManagement.java
  src/main/java/com/cloudbees/jenkins/support/filter/AllContentFilters.java
  src/main/java/com/cloudbees/jenkins/support/filter/ContentFilter.java
  src/main/java/com/cloudbees/jenkins/support/filter/ContentFilters.java
  src/main/java/com/cloudbees/jenkins/support/filter/ContentMapping.java
  src/main/java/com/cloudbees/jenkins/support/filter/ContentMappings.java
  src/main/java/com/cloudbees/jenkins/support/filter/DataFaker.java
  src/main/java/com/cloudbees/jenkins/support/filter/FilteredOutputStream.java
  src/main/java/com/cloudbees/jenkins/support/filter/FilteredWriter.java
  src/main/java/com/cloudbees/jenkins/support/filter/InetAddressContentFilter.java
  src/main/java/com/cloudbees/jenkins/support/filter/NameProvider.java
  src/main/java/com/cloudbees/jenkins/support/filter/SensitiveContentFilter.java
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
  src/main/java/com/cloudbees/jenkins/support/impl/AdvancedProcFilesRetriever.java
  src/main/java/com/cloudbees/jenkins/support/impl/GCLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/SlaveCommandStatistics.java
  src/main/java/com/cloudbees/jenkins/support/impl/ThreadDumps.java
  src/main/java/com/cloudbees/jenkins/support/util/Helper.java
  src/main/java/com/cloudbees/jenkins/support/util/IgnoreCloseOutputStream.java
  src/main/java/com/cloudbees/jenkins/support/util/IgnoreCloseWriter.java
  src/main/java/com/cloudbees/jenkins/support/util/Markdown.java
  src/main/java/com/cloudbees/jenkins/support/util/OutputStreamSelector.java
  src/main/java/com/cloudbees/jenkins/support/util/Persistence.java
  src/main/java/com/cloudbees/jenkins/support/util/WrapperOutputStream.java
  src/test/java/com/cloudbees/jenkins/support/BundleFileNameTest.java
  src/test/java/com/cloudbees/jenkins/support/BundleNamePrefixTest.java
  src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
  src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
Labels: dependencies

#348 [JENKINS-68008] Remove unnecessary usage of AHCUtils
  pom.xml
  src/main/java/com/cloudbees/jenkins/support/impl/UpdateCenter.java
  src/test/java/com/cloudbees/jenkins/support/impl/UpdateCenterTest.java
Labels: dependencies

#350 Use `systemPropertyVariables` rather than `argLine`
  pom.xml
Labels: enhancement

#353 PCT: Adapt test for 2.340 structure changes
  src/test/java/com/cloudbees/jenkins/support/SupportTestUtils.java
Labels: bug, chore
