Repository jenkinsci/support-core-plugin, pull requests merged in 2023-08, with the labels that each got.

#483 Diagnostics for flake in `FileDescriptorLimitTest.agentContentFilter`
  src/main/java/com/cloudbees/jenkins/support/AsyncResultCache.java
  src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
Labels: developer

#484 [JENKINS-71732] Add component to collect executors information
  src/main/java/com/cloudbees/jenkins/support/impl/NodeExecutors.java
  src/test/java/com/cloudbees/jenkins/support/impl/NodeExecutorsTest.java
Labels: feature

#485 [JENKINS-71722][JENKINS-71758] Respect globally configured period for Periodic generation
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration.java
  src/main/resources/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration/config.jelly
  src/main/resources/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfiguration/config.properties
  src/main/resources/com/cloudbees/jenkins/support/config/SupportPluginManagement/index.jelly
  src/test/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfigurationSystemPropertiesTest.java
  src/test/java/com/cloudbees/jenkins/support/config/SupportAutomatedBundleConfigurationTest.java
Labels: bug

#487 Simplification of `CallAsyncWrapper`
  src/main/java/com/cloudbees/jenkins/support/util/CallAsyncWrapper.java
Labels: chore

#486 More diagnostics for `FileDescriptorLimitTest` flake
  src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
Labels: developer

#489 Giving up on flake in `FileDescriptorLimitTest.agentContentFilter`
  src/test/java/com/cloudbees/jenkins/support/impl/FileDescriptorLimitTest.java
Labels: developer
