Repository jenkinsci/support-core-plugin, pull requests merged in 2023-02, with the labels that each got.

#429 Use `SafeTimerTask.getLogsRoot`
  src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/TaskLogs.java
Labels: chore

#430 Removing junk file `.cloudbees.md`
  .cloudbees.md
Labels: chore

#436 Avoid NPE when `Computer.getNode` returns null
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Labels: bug

#434 Jenkins logs should be colocated
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/impl/JenkinsLogs.java
  src/main/java/com/cloudbees/jenkins/support/impl/SmartLogCleaner.java
  src/main/java/com/cloudbees/jenkins/support/impl/SmartLogFetcher.java
  src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
  src/test/java/com/cloudbees/jenkins/support/impl/SmartLogCleanerTest.java
Labels: chore

#437 Make `ContentContainer.contents` thread-safe
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
Labels: bug

#443 [JENKINS-70653] Add stricter default includes in Node directory compo…
  src/main/java/com/cloudbees/jenkins/support/impl/NodeRemoteDirectoryComponent.java
  src/main/resources/com/cloudbees/jenkins/support/impl/DirectoryComponent/help-includes.html
Labels: enhancement

#444 [JENKINS-70703] Expose in the UI that the DownloadBundle permission is deprecated, as per SECURITY-2804
  src/main/resources/com/cloudbees/jenkins/support/Messages.properties
Labels: enhancement
