Repository jenkinsci/support-core-plugin, pull requests merged in 2024-05, with the labels that each got.

#544 [doc] Remove misleading javadoc comment
  src/main/java/com/cloudbees/jenkins/support/api/ObjectComponent.java
Labels: chore

#543 Forward compatibility with EE 9
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
Labels: developer

#542 [chore] No point for CustomLogs to be enabled by default
  src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
Labels: enhancement

#545 Remove usages of Commons Compress
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
Labels: developer
