Repository jenkinsci/support-core-plugin, pull requests merged in 2024-09, with the labels that each got.

#558 THREAD_DUMPS_ON_SLOW_REQUEST: adding the base of the development of t…
  src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestChecker.java
  src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestThreadDumpsComponent.java
  src/main/java/com/cloudbees/jenkins/support/slowrequest/SlowRequestThreadDumpsGenerator.java
Labels: enhancement

#576 [JENKINS-73712] Anonymize OldDataMonitor details in admin-monitors.md
  src/main/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitors.java
  src/test/java/com/cloudbees/jenkins/support/impl/AdministrativeMonitorsTest.java
Labels: bug

#577 [chore] Add "up" and "running" as stop words
  src/main/java/com/cloudbees/jenkins/support/filter/DefaultStopWords.java
Labels: enhancement, chore

#580 Add ability to filter more Config Files from OtherConfigFilesComponent
  README.md
  src/main/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponent.java
  src/test/java/com/cloudbees/jenkins/support/configfiles/OtherConfigFilesComponentTest.java
Labels: feature
