Repository jenkinsci/support-core-plugin, pull requests merged in 2024-10, with the labels that each got.

#589 Work around NPE in `Stapler.getCurrent`
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
Labels: chore

#590 JENKINS-73984: More efficient filtering of input streams
  src/main/java/com/cloudbees/jenkins/support/api/LaunchLogsFileContent.java
  src/main/java/com/cloudbees/jenkins/support/filter/FilteredInputStream.java
  src/test/java/com/cloudbees/jenkins/support/filter/FilteredInputStreamTest.java
Labels: bug

#592 Removing `AgentProtocols`
  src/main/java/com/cloudbees/jenkins/support/impl/AgentProtocols.java
  src/test/java/com/cloudbees/jenkins/support/impl/AgentProtocolsTest.java
Labels: enhancement
