Repository jenkinsci/support-core-plugin, pull requests merged in 2024-03, with the labels that each got.

#514 Removing old changelog
  CHANGELOG.md
  README.md
Labels: documentation

#513 Deleting unnecessary Release Drafter config
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#512 Removing duplicate `dependency`
  pom.xml
Labels: chore

#516 Fix javac warning in `new Content(String)`
  src/main/java/com/cloudbees/jenkins/support/api/Content.java
  src/test/java/com/cloudbees/jenkins/support/util/Chrono.java
Labels: chore

#511 Replace class restriction to method levels of ContentMappings
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/filter/ContentFilter.java
Labels: developer

#515 Update baseline to 2.414.x
  Jenkinsfile
  pom.xml
  src/test/java/com/cloudbees/jenkins/support/impl/NodeExecutorsTest.java
Labels: developer

#519 Define `Container.getComponents`
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/api/Container.java
Labels: developer

#522 Trying to deflake `CheckFilterTest`
  src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
Labels: developer

#523 NPE in `AboutJenkins`
  src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java
Labels: bug

#517 Overhaul of `SlaveLaunchLogs`
  pom.xml
  src/main/java/com/cloudbees/jenkins/support/api/LaunchLogsFileContent.java
  src/main/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogs.java
  src/test/java/com/cloudbees/jenkins/support/Security2186Test.java
  src/test/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogsRestartTest.java
  src/test/java/com/cloudbees/jenkins/support/impl/SlaveLaunchLogsTest.java
Labels: bug

#525 Fixes to `RunDirectoryComponent.excludes`
  src/main/java/com/cloudbees/jenkins/support/impl/AbstractItemDirectoryComponent.java
  src/main/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponent.java
  src/main/resources/com/cloudbees/jenkins/support/impl/AbstractItemDirectoryComponent/help.html
  src/main/resources/com/cloudbees/jenkins/support/impl/DirectoryComponent/help-excludes.html
  src/main/resources/com/cloudbees/jenkins/support/impl/DirectoryComponent/help-includes.html
  src/main/resources/com/cloudbees/jenkins/support/impl/RunDirectoryComponent/help.html
  src/test/java/com/cloudbees/jenkins/support/impl/AbstractItemDirectoryComponentTest.java
  src/test/java/com/cloudbees/jenkins/support/impl/RunDirectoryComponentTest.java
Labels: bug
