Repository jenkinsci/support-core-plugin, pull requests merged in 2025-02, with the labels that each got.

#624 Stop agents before exiting test cases, and reliably close `all_*.log` when agents exit
  pom.xml
  src/main/java/com/cloudbees/jenkins/support/SupportLogHandler.java
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/test/java/com/cloudbees/jenkins/support/impl/SmartLogCleanerTest.java
Labels: bug

#628 Improve output on NodeRemoteDirectoryComponentTest failures
  src/test/java/com/cloudbees/jenkins/support/impl/NodeRemoteDirectoryComponentTest.java
Labels: tests

#617 Generate support bundle Async
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportObjectAction.java
  src/main/java/com/cloudbees/jenkins/support/api/Component.java
  src/main/java/com/cloudbees/jenkins/support/impl/AboutBrowser.java
  src/main/java/com/cloudbees/jenkins/support/impl/ReverseProxy.java
  src/main/resources/com/cloudbees/jenkins/support/SupportAction/index.jelly
  src/main/resources/com/cloudbees/jenkins/support/SupportAction/progressPage.jelly
  src/main/resources/js/progressPage.js
  src/test/java/com/cloudbees/jenkins/support/SupportActionTest.java
Labels: enhancement

#623 Removing `requesterAuthentication`
  src/main/java/com/cloudbees/jenkins/support/SupportAction.java
  src/main/java/com/cloudbees/jenkins/support/SupportCommand.java
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/actions/SupportObjectAction.java
  src/main/java/com/cloudbees/jenkins/support/impl/AboutUser.java
  src/test/java/com/cloudbees/jenkins/support/CheckFilterTest.java
Labels: chore

#629 Close all files in `CustomLogsTest`
  src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
  src/test/java/com/cloudbees/jenkins/support/impl/CustomLogsTest.java
Labels: tests

#627 Adding rolled custom logs in support bundle
  src/main/java/com/cloudbees/jenkins/support/impl/CustomLogs.java
  src/test/java/com/cloudbees/jenkins/support/impl/CustomLogsTest.java
Labels: enhancement
