Repository jenkinsci/support-core-plugin, pull requests merged in 2025-01, with the labels that each got.

#601 API to supersede components if not required
  src/main/java/com/cloudbees/jenkins/support/SupportPlugin.java
  src/main/java/com/cloudbees/jenkins/support/api/Component.java
  src/test/java/com/cloudbees/jenkins/support/SupportPluginTest.java
Labels: developer

#612 Relax assertion in `NodeExecutorsTest`
  src/test/java/com/cloudbees/jenkins/support/impl/NodeExecutorsTest.java
Labels: developer

#611 NPE in `AgentsConfigFile.addContents`
  src/main/java/com/cloudbees/jenkins/support/configfiles/AgentsConfigFile.java
Labels: bug

#613 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: dependencies, java
